feat: Create edit card component
re-taro/alibum pull request #63
Opened 2022-12-11 18:27 UTC by Sansai-snct

Close #25 

使用イメージ↓
![スクリーンショット 2022-12-12 3 21 27](https://user-images.githubusercontent.com/62200647/206921728-ffcb740c-c543-473e-ae63-170d8bcd8db3.png)

2022-12-11 20:21 UTC, Bayathy requested changes

2022-12-11 20:24 UTC, Bayathy submitted a review, later dismissed

2022-12-11 20:24 UTC, Bayathy commented on src/components/card/edit.tsx
> +};
```suggestion
type EditCardProps = {
  text: string;
  imageref?: string;
};
```

2022-12-11 20:31 UTC, Bayathy commented on src/components/card/edit.tsx
> +};
```
ViewCard.defaultProps = {
  imageref: undefined
}
```
この型定義にするとeslint[react/require-default-props](https://github.com/jsx-eslint/eslint-plugin-react/tree/master/docs/rules/require-default-props.md)
のエラーが出て、こういう書き方してほしいらしいけどほか二人に任せます

2022-12-11 22:45 UTC, re-taro requested changes

2022-12-11 23:00 UTC, re-taro requested changes

2022-12-11 23:00 UTC, re-taro commented on src/components/card/edit.tsx
> +      width="70vw"
これなんでwidth 70vwなんですか？デザインの限りそうだとは思えないんだけど

2022-12-11 23:08 UTC, Bayathy commented on src/components/card/edit.tsx
> +      width="70vw"
```
      w="full"
      px={base: 10, lg:34}
```
でデザイン通りかな

2022-12-11 23:09 UTC, Bayathy commented on src/components/card/edit.tsx
> +              <Image
@Sansai-snct 
ここ触ったの俺やけどもしやる場合は頼める？

2022-12-11 23:23 UTC, re-taro commented on src/components/card/edit.tsx
> +      width="70vw"
ああ、paddingはカードの外側で持たせるよ？

2022-12-11 23:24 UTC, Bayathy commented on src/components/card/edit.tsx
> +type EditCardProps = {
あコードの選択ミスってる
typeの話

2022-12-11 23:26 UTC, Bayathy commented on src/components/card/edit.tsx
> +      width="70vw"
あーおけ

2022-12-11 23:27 UTC, Bayathy commented on src/components/card/edit.tsx
> +      width="70vw"
てかこれそもそもpaddingじゃなくてmarginだな

2022-12-11 23:28 UTC, Sansai-snct commented on src/components/card/edit.tsx
> +  imageref ? (
単純に昨日三項演算子以外思い浮かばなかったっていうアレ

2022-12-11 23:31 UTC, Sansai-snct commented on src/components/card/edit.tsx
> +};
型undefinedにするのなんか嫌だからルール無効化した方が好みなんだけどどうなんだろ

2022-12-11 23:39 UTC, Sansai-snct commented on src/components/card/edit.tsx
> +      width="70vw"
ノリで当てたのそのままにしてたわ自害

2022-12-11 23:41 UTC, re-taro commented on src/components/card/edit.tsx
> +};
無効のが良い。T| undefindのユニオンだと明示的に指定する必要あるから

2022-12-11 23:47 UTC, Sansai-snct commented on src/components/card/edit.tsx
> +type EditCardProps = {
`export  type CardProps`とかにして共通化する？

2022-12-11 23:52 UTC, re-taro commented on src/components/card/edit.tsx
> +type EditCardProps = {
そうやね。componets/card/types.ts とかに置いておいてもらえると

2022-12-11 23:55 UTC, Sansai-snct commented on src/components/card/edit.tsx
> +  imageref ? (
あー実装思いついた

2022-12-12 01:48 UTC, Sansai-snct commented on src/components/card/edit.tsx
> +  imageref ? (
[099c44f](https://github.com/re-taro/alibum/pull/63/commits/099c44f3a18aa03483e014946b68eab35525dd41)
なんでこれしなかったんだろ

2022-12-12 01:49 UTC, Sansai-snct commented on src/components/card/edit.tsx
> +};
[a566c2c](https://github.com/re-taro/alibum/pull/63/commits/a566c2c19cc379ed292b8170b287db061148d6d2)

2022-12-12 01:49 UTC, Sansai-snct commented on src/components/card/edit.tsx
> +type EditCardProps = {
[a566c2c](https://github.com/re-taro/alibum/pull/63/commits/a566c2c19cc379ed292b8170b287db061148d6d2)

2022-12-12 01:51 UTC, re-taro requested changes

2022-12-12 01:51 UTC, re-taro commented on src/components/card/edit.tsx
> +              visibility={{ visibility: imageref ? "visible" : "hidden" }}
これ要らんくない？

2022-12-12 01:58 UTC, Sansai-snct commented on src/components/card/edit.tsx
> +              visibility={{ visibility: imageref ? "visible" : "hidden" }}
うわごめん試したやつの消し忘れや

2022-12-12 09:35 UTC, re-taro commented on src/components/card/edit.tsx
> +              <Image
これ不可能

2022-12-12 09:45 UTC, re-taro approved these changes

2022-12-12 09:46 UTC, merged

2022-12-12 09:50 UTC, Bayathy approved these changes