add:Adding Dynamic Messages,Font unification
re-taro/alibum pull request #76
Opened 2022-12-14 06:10 UTC by nekoshark02

Fixed a problem with feat/#30. ogp now supports dynamic comments.

2022-12-14 15:57 UTC, re-taro requested changes
fontがサブセット化されていないようにみえるのでしてください。

2022-12-14 15:57 UTC, re-taro commented on yarn.lock
> +"@vercel/og@npm:^0.0.21":
yarn.lockを更新してください

2022-12-14 15:57 UTC, re-taro commented on src/pages/api/og.tsx
> +    {
ここで絵文字の種類も決めれます。docを読んで下さい

2022-12-14 15:57 UTC, re-taro commented on src/pages/api/og.tsx
> +          style: "normal",
fontWidthを設定してください

2022-12-14 15:57 UTC, re-taro commented on src/pages/api/og.tsx
> +        <option style={{
いらない

2022-12-14 15:57 UTC, re-taro commented on src/pages/api/og.tsx
> +import { NextRequest } from 'next/server';
type importを行ってください

2022-12-14 15:57 UTC, re-taro commented on src/pages/api/og.tsx
> +    : "My default title";
ないなら""でいいです。それかalibum

2022-12-14 15:57 UTC, re-taro commented on src/pages/api/og.tsx
> +export default async (req: NextRequest) => {
名前をつけてください。

2022-12-15 15:44 UTC, re-taro requested changes

2022-12-15 15:53 UTC, re-taro requested changes
subsetするときなんの文字を指定した？

2022-12-15 16:06 UTC, nekoshark02 commented
> この記事の「カスタムフォントを使用する」という章にあった文字一覧をサブセット化に使いました
[【デザイン不要】@vercel/ogを使っていい感じの動的OGPをつくる](https://zenn.dev/hiromu617/articles/c03fef6f4d6c6e)

2022-12-15 16:38 UTC, re-taro requested changes
あ、変数とかはCamelcaseである必要なくて、"Alibunm"だけで良かったです

2022-12-15 17:43 UTC, re-taro commented
yarn.lockのコンフリクトだけ直しておいてね

2022-12-16 17:03 UTC, re-taro approved these changes

2022-12-16 17:03 UTC, merged