Create edit page
re-taro/alibum pull request #92
Opened 2022-12-15 16:15 UTC by Sansai-snct

Close #24

2022-12-15 16:16 UTC, Sansai-snct commented
HeaderのPropsとtitleが地獄すぎて泣ける

2022-12-16 15:41 UTC, re-taro requested changes

2022-12-16 15:41 UTC, re-taro commented on src/components/layout/edit.tsx
> +import { FC, ReactNode, ReactElement, useEffect, useState } from "react";
type importを使いましょう

2022-12-16 15:41 UTC, re-taro commented on src/components/layout/edit.tsx
> +import { getInfo } from "libs/firebase/store";
importを直してください

2022-12-16 15:41 UTC, re-taro commented on src/components/layout/edit.tsx
> +        setListid(i);
これでいいと思う。冗長

```suggestion
        setListid(id as string);
```

2022-12-16 15:41 UTC, re-taro commented on src/components/layout/edit.tsx
> +  }, [router, listid]);
routerが変わるとき = listidが変わるときなのでここの依存は冗長だと思う。

2022-12-16 15:41 UTC, re-taro commented on src/components/layout/edit.tsx
> +  const [listid, setListid] = useState("0");
これstateにする必要ある？

2022-12-16 15:41 UTC, re-taro commented on src/components/layout/header/edit.tsx
> +  });
依存を持たせてもらえますか

2022-12-16 15:41 UTC, re-taro commented on src/components/layout/header/edit.tsx
> +        label="link"
linkではない

2022-12-16 15:41 UTC, re-taro commented on src/libs/firebase/store.ts
> +  DocumentData,
CollectionReference,DocumentDataって型じゃないですか？type importしてください

2022-12-16 15:41 UTC, re-taro commented on src/pages/edit/[id].tsx
> +import { useRef, useEffect, useState, Suspense } from "react";
```suggestion
import { useRef, useEffect, useState } from "react";
```

2022-12-16 15:41 UTC, re-taro commented on src/pages/edit/[id].tsx
> +  const listid = id;
これ何用ですか

2022-12-16 15:41 UTC, re-taro commented on src/pages/edit/[id].tsx
> +  const [title, setTitle] = useState("");
useStateは同じところ(上の方)にまとめてほしいです

2022-12-16 15:41 UTC, re-taro commented on src/pages/edit/[id].tsx
> +  const { register, handleSubmit, reset } = useForm<CreateStoreCardListItem>();
defaultValueを持たせてください

2022-12-16 15:41 UTC, re-taro commented on src/pages/edit/[id].tsx
> +  const { register, handleSubmit, reset } = useForm<CreateStoreCardListItem>();
mode: "onBlur"を追加してください

2022-12-16 15:41 UTC, re-taro commented on src/pages/edit/[id].tsx
> +  const onFileInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
globalなReact namespaceを使わないでください

2022-12-16 15:41 UTC, re-taro commented on src/pages/edit/[id].tsx
> +  const [image, setImage] = useState("");
命名が不適切。
imageUrlとかにしてください

2022-12-16 15:41 UTC, re-taro commented on src/pages/edit/[id].tsx
> +          placeholder="//感謝を綴ろう"
place holderからヲタクを感じます
```suggestion
          placeholder="感謝を綴ろう"
```

2022-12-16 15:41 UTC, re-taro commented on src/pages/edit/[id].tsx
> +          <Image width={128} height={128} src={image} alt={image} />
@Bayathy の画像がいい感じになる実装に変えたらましになると思います

2022-12-16 15:41 UTC, re-taro commented on src/pages/edit/[id].tsx
> +          <Image width={128} height={128} src={image} alt={image} />
altをサボるな

2022-12-16 16:14 UTC, Sansai-snct commented on src/pages/edit/[id].tsx
> +          <Image width={128} height={128} src={image} alt={image} />
[2ae159e](https://github.com/re-taro/alibum/pull/92/commits/2ae159e9a355d45860c7ba79b37dd799d1a93289)

2022-12-16 16:15 UTC, Sansai-snct commented on src/pages/edit/[id].tsx
> +          placeholder="//感謝を綴ろう"
[2ae159e](https://github.com/re-taro/alibum/pull/92/commits/2ae159e9a355d45860c7ba79b37dd799d1a93289)

2022-12-16 16:15 UTC, Sansai-snct commented on src/pages/edit/[id].tsx
> +  const [image, setImage] = useState("");
[2ae159e](https://github.com/re-taro/alibum/pull/92/commits/2ae159e9a355d45860c7ba79b37dd799d1a93289)

2022-12-16 16:15 UTC, Sansai-snct commented on src/components/layout/edit.tsx
> +  const [listid, setListid] = useState("0");
[15748a7](https://github.com/re-taro/alibum/pull/92/commits/15748a710b34750862b4fd4dc238349fc688501b)

2022-12-16 16:16 UTC, Sansai-snct commented on src/pages/edit/[id].tsx
> +  const onFileInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
[dfbc202](https://github.com/re-taro/alibum/pull/92/commits/dfbc2023a2dc3ce82f9a3e8cf0951640ace07703)

2022-12-16 16:16 UTC, Sansai-snct commented on src/pages/edit/[id].tsx
> +import { useRef, useEffect, useState, Suspense } from "react";
[dfbc202](https://github.com/re-taro/alibum/pull/92/commits/dfbc2023a2dc3ce82f9a3e8cf0951640ace07703)

2022-12-16 16:16 UTC, Sansai-snct commented on src/libs/firebase/store.ts
> +  DocumentData,
[dfbc202](https://github.com/re-taro/alibum/pull/92/commits/dfbc2023a2dc3ce82f9a3e8cf0951640ace07703)

2022-12-16 16:18 UTC, Sansai-snct commented on src/pages/edit/[id].tsx
> +  const [title, setTitle] = useState("");
[15748a7](https://github.com/re-taro/alibum/pull/92/commits/15748a710b34750862b4fd4dc238349fc688501b)

2022-12-16 16:18 UTC, Sansai-snct commented on src/pages/edit/[id].tsx
> +  const { register, handleSubmit, reset } = useForm<CreateStoreCardListItem>();
[15748a7](https://github.com/re-taro/alibum/pull/92/commits/15748a710b34750862b4fd4dc238349fc688501b)

2022-12-16 16:18 UTC, Sansai-snct commented on src/pages/edit/[id].tsx
> +  const { register, handleSubmit, reset } = useForm<CreateStoreCardListItem>();
[15748a7](https://github.com/re-taro/alibum/pull/92/commits/15748a710b34750862b4fd4dc238349fc688501b)

2022-12-16 16:19 UTC, Sansai-snct commented on src/components/layout/edit.tsx
> +        setListid(i);
[1beef82](https://github.com/re-taro/alibum/pull/92/commits/1beef82c61b8da9875685a781735c3d065ac09d7)

2022-12-16 16:19 UTC, Sansai-snct commented on src/components/layout/edit.tsx
> +  }, [router, listid]);
[1beef82](https://github.com/re-taro/alibum/pull/92/commits/1beef82c61b8da9875685a781735c3d065ac09d7)

2022-12-16 16:20 UTC, Sansai-snct commented on src/components/layout/edit.tsx
> +import { FC, ReactNode, ReactElement, useEffect, useState } from "react";
[f20d008](https://github.com/re-taro/alibum/pull/92/commits/f20d0081f7c39566ea7576d6cf3878af82accb84)

2022-12-16 16:21 UTC, Sansai-snct commented on src/components/layout/edit.tsx
> +import { getInfo } from "libs/firebase/store";
[f20d008](https://github.com/re-taro/alibum/pull/92/commits/f20d0081f7c39566ea7576d6cf3878af82accb84)

2022-12-16 16:21 UTC, Sansai-snct commented on src/components/layout/header/edit.tsx
> +  });
[d7fc9ec](https://github.com/re-taro/alibum/pull/92/commits/d7fc9ec7e22c39a0c475175ab0cdca5205e432fa)

2022-12-16 16:22 UTC, Sansai-snct commented on src/components/layout/header/edit.tsx
> +        label="link"
[7d28694](https://github.com/re-taro/alibum/pull/92/commits/7d28694c7bbcc434c5d92f90118702d38e43b41f)

2022-12-16 16:28 UTC, Sansai-snct commented on src/pages/edit/[id].tsx
> +  const listid = id;
userはsubmitとかでuser.uid使うためのもの
imageはPreview用imageUrl
fileは...registerで取り扱おうとするとキモくて逃げた
listidは冗長

2022-12-16 16:28 UTC, Sansai-snct commented on src/pages/edit/[id].tsx
> +  const listid = id;
[05d57df](https://github.com/re-taro/alibum/pull/92/commits/05d57dfed77921f6e65d8546546bc93fc2f10585)

2022-12-16 16:35 UTC, Sansai-snct commented on src/pages/edit/[id].tsx
> +          <Image width={128} height={128} src={image} alt={image} />
[932f7f6](https://github.com/re-taro/alibum/pull/92/commits/932f7f6ea5a6ca126b09abc7fc2826a2d18bd6c5)

2022-12-16 16:49 UTC, re-taro approved these changes

2022-12-16 16:49 UTC, merged